# Generated by Django 3.2.4 on 2021-06-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_picture.png', upload_to='images/'),
        ),
    ]
